.vscode/settings.json
models/repo.js
models/user.js

Create repo sequelize model

---

models/settings.js
models/user.js

added settings model

---

views/layouts/main.handlebars

Added main.handlebars

---

public/index.html
routes/html-routes.js

Added index, login, signup, dashboard html routing

---

controllers/user.js
public/js/login.js
public/js/signup.js
public/login.html
public/signup.html

Client-side login and sign in functionality

---

middleware/getUserInfo.js
package-lock.json
package.json

Added axios request to get user data from github

---

middleware/getUserInfo.js

Added axios call for user's repos

---

routes/html-routes.js
views/index.handlebars
views/layouts/main.handlebars
views/partials/navbar.handlebars

converted index to handlebars and added navbar partial

---

views/login.handlebars
views/signup.handlebars

Added headers to login and signup

---

views/layoutOne.handlebars

added navabar on layoutOne

---

config/middleware/isAuthenticated.js
controllers/dashboard.js
controllers/repo.js
controllers/user.js
middleware/getUserInfo.js
models/repo.js
models/user.js
public/js/dashboard.js
routes/api-routes.js
routes/html-routes.js
server.js
views/dashboard.handlebars
views/layouts/main.handlebars
views/login.handlebars
views/signup.handlebars

Dashboard javascript

---

routes/html-routes.js
views/index.handlebars

changes made to index handlebars

---

views/dashboard.handlebars

Change dashboard.handlebars to reflect no repos found

---

views/index.handlebars
views/layout1.handlebars
views/partials/navbar.handlebars

changes to navbar

---

public/js/dashboard.js
views/dashboard.handlebars

Fix repo slider toggle, OCD indentation on dashboard.handlebars

---

README.md

removed inspiration section from readme file

---

controllers/admin.js
public/js/admin.js
views/admin.handlebars

added delete btn functionallity on admin dashboard

---

views/admin.handlebars

duplicate delet btn removed from admin handlebars

---

config/config.json
controllers/repo.js
middleware/getUserInfo.js
middleware/isAuthenticated.js
models/repo.js
package.json
views/dashboard.handlebars

Better logic with update/destroy/create

---

README.md
views/admin.handlebars

added reployed link to readme file

---

views/index.handlebars

imgs added to homepage

---

views/index.handlebars

center text with images on home page(see image in comment)
